name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@master
      - name: setup pythone3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install mkdocs-material
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-plugin
          mkdocs build
        env:
          CI: true
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "site/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}